server:
  port: 1010
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: null
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
product:
  messages:
    saveSuccess: Product saved Successfully
    updateSuccess: Product updated Successfully
    failSave: Fail to saved Product